---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

#RESISTOME DIVERSITY ANALYSES

##Activating libraries
```{r}
library(tidyverse)
library("ggsci") 
library(ggpubr)
library(rstatix)
```


#Importing tables
```{r}
setwd("~/OneDrive\ -\ Michigan\ State\ University/Manning_lab/Mastitis_project/GitHub/data/")

#Metadata
metadata =read.table("metadata.csv", sep = ",", header = TRUE,  na.strings = "") %>% 
   filter(Time_tx %in% c("Day -1","Week 1","Week 5", "Week 9"))
metadata$days_tx <- as.numeric(as.character(metadata$days_tx))
metadata$Treatment <- factor(metadata$Treatment, levels = c("Control","Antibiotic"))


#Alpha diversity (shannon, simpson, chao1) calculated through the COSMOS-ID pipeline
alpha =read.table("alpha_ARGs_abs_COSMOS-ID.tsv", sep = "\t", header = TRUE,  na.strings = "") 

#Beta diversity (Jaccard & Bray-curtis dissimilarity) calculated through the COSMOS-ID pipeline
beta = read.table("betapca_ARGs_abs_COSMOS-ID.tsv", sep = "\t", header = TRUE,  na.strings = "") 

#ARGs abundance score calculated through the COSMOS-ID pipeline
abundance = read.table("abundance_ARGs_abs_COSMOS-ID.tsv", sep = "\t", header = TRUE,  na.strings = "", check.names = F)
```

#MERGING TABLES
```{r}
alpha_met <- merge(metadata,alpha,by="Name")
alpha_beta_met <- merge(beta,alpha_met,by="Name")
alpha_beta_met$Treatment <- factor(alpha_beta_met$Treatment, levels = c("Control","Antibiotic"))
```

#ALPHA DIVERSITY
##Shannon
```{r}
library(rstatix)
#Calculating p-value for the variation over time
stat.test_time <- alpha_beta_met %>%
  kruskal_test(Shannon ~ Time_tx)
stat.test_time
```

```{r}
library(rstatix)
#Calculating p-values between treatments by time point
stat.test <- alpha_beta_met %>%
  group_by(Time_tx) %>%
  wilcox_test(Shannon ~ Treatment, alternative = "less") %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj") %>%
  add_xy_position(x = "Time_tx", dodge = 0.8)

stat.test
```

```{r}
library(ggpubr)
library(ggsci)

#Boxplot of Shannon diversity between treatment groups over time
shannon_boxplot_ARG = ggboxplot(alpha_beta_met, x = "Time_tx", y = "Shannon", color = "Treatment", palette = "jama", fill = "Treatment", add = c("jitter"), notch = F, outlier.shape = NA) +
  labs(x = "Time to treatment", y = "Shannon index", colour = "Treatment", fill = "Treatment") + 
  scale_fill_jama(alpha = 0.5) +
  stat_pvalue_manual(stat.test,  label = "p", tip.length = 0) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  annotate("text", x = 2.5, y = 5.5, label = expression(paste("Kruskal-Wallis, ", paste(italic('p'))," = 1.73e-05"))) +
  geom_signif(aes(y = Shannon, x = Time_tx),
              comparisons = list(c("Day -1","Week 1"),c("Week 1","Week 5"),c("Week 5","Week 9") ), 
              test = "wilcox.test", y_position = c(3.2,3.4,4.7), color = "gray35", tip_length = 0.02)  +
  theme(axis.title.x = element_blank())

shannon_boxplot_ARG
```
##CHAO1
```{r}
library(rstatix)
#Calculating p-value for the variation over time
stat.test_time <- alpha_beta_met %>%
  kruskal_test(Chao1 ~ Time_tx)
stat.test_time
```

```{r}
#Calculating p-values between treatments by time point
stat.test <- alpha_beta_met %>%
  group_by(Time_tx) %>%
  wilcox_test(Chao1 ~ Treatment, alternative = "less") %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj") %>% 
  add_xy_position(x = "Time_tx", dodge = 0.8)

stat.test
```

```{r}
chao1_ARG_boxplot = ggboxplot(alpha_beta_met, x = "Time_tx", y = "Chao1", color = "Treatment", palette = "jama", fill = "Treatment", add = c("jitter"), notch = F, outlier.shape = NA) +
  labs(x = "Time to treatment", y = "Chao1 index", colour = "Treatment", fill = "Treatment") + 
  scale_fill_jama(alpha = 0.5)  + 
  stat_pvalue_manual(stat.test,  label = "p", tip.length = 0) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  annotate("text", x = 2.5, y = 85, label = expression(paste("Kruskal-Wallis, ", paste(italic('p'))," = 0.045"))) +
  geom_signif(aes(y = Chao1, x = Time_tx),
              comparisons = list(c("Day -1","Week 1"),c("Week 1","Week 5"),c("Week 5","Week 9") ), 
              test = "wilcox.test", y_position = c(50,60,75), color = "gray35", tip_length = 0.02) +
  theme(axis.title.x = element_blank())

chao1_ARG_boxplot
```

#BETA-DIVERSITY
#Bray ordination with densities
```{r}
library(cowplot)
library("scales")
library(ggthemes)

#Permanova value provided by COSMOS-ID
label_perm <- expression(paste("PERMANOVA, ",F ,"= 4.278, ",paste(italic('p')),"=0.001"))

#PCoA of the Bray-Curtis dissimilarity 
pmain_brayF = ggscatter(alpha_beta_met, x = "bray_curtis.X", y = "bray_curtis.Y", color = "Time_tx", shape = "Treatment",ellipse = TRUE, ellipse.level=.7,mean.point = F, mean.point.size = 5, star.plot = F) +
  labs(x = "PCoA 1 (32.58%) ", y = "PCoA 2 (16.04%)", colour = "Time", fill = "Time") + 
  theme(legend.position = "top") +
  scale_fill_colorblind() +   
  scale_color_colorblind() +
  annotate("text", x = -0.1, y = 0.2, label = label_perm, colour = "black", size = 4)

#Adding marginal densities along x axis in the PCoA
xdens <- axis_canvas(pmain_brayF, axis = "x") +
  geom_density(data = alpha_beta_met, aes(x = bray_curtis.X, fill = Time_tx), alpha = 0.7, size = 0.2) +
  theme(legend.position = "none") +
  scale_fill_colorblind()

#Adding marginal densities along x axis in the PCoA
ydens <- axis_canvas(pmain_brayF, axis = "y", coord_flip = TRUE) +
  theme(legend.position = "none") +
  geom_density(data = alpha_beta_met, aes(x = bray_curtis.Y, fill = Time_tx), alpha = 0.7, size = 0.2)+
  coord_flip() +
  scale_fill_colorblind()

#Inserting densities in the PCoA plot
p1 <- insert_xaxis_grob(pmain_brayF, xdens, grid::unit(.2, "null"), position = "top")
p2<- insert_yaxis_grob(p1, ydens, grid::unit(.2, "null"), position = "right")

#Ploting the PCoA
bray_plotARG = ggdraw(p2)
bray_plotARG
```


#ABUNDANCE
##Class
```{r}
library(reshape2)
#Adding all the abundances at the Class level
ARG_class_ab <- abundance %>% 
  dplyr::select(Drug_Class, 6:164) %>% 
  group_by(Drug_Class) %>% 
  summarise_all(sum)

#Transposing table and merging with the metadata
ARG_class_ab_metadata <- melt(ARG_class_ab, id = colnames(ARG_class_ab)[1]) %>% 
  rename(Name = variable, Abundance = value) %>% 
  merge(metadata,by="Name")
```

```{r}
ARG_class_ab_barplot <- ARG_class_ab_metadata %>% 
  ggbarplot(x= "Time_tx", y = "Abundance", color = "Drug_Class", fill = "Drug_Class", 
            palette = get_palette("npg",10), 
            ylab = "Relative abundance", 
            legend = "right", 
            position = position_fill()) +
  labs(fill="ARG Class", color="ARG Class") +
  facet_grid(~Treatment, scales = "free_x", space = "free_x") +
  theme(axis.title.x = element_blank())

ARG_class_ab_barplot
```

##ARGs
```{r}
library(reshape2)
#Adding all the abundances at the ARG-group level
ARG_gene_ab <- abundance %>% 
  dplyr::select(ARG_group, 6:164) %>% 
  group_by(ARG_group) %>% 
  summarise_all(sum)

#Transposing table and merging with the metadata
ARG_ab_metadata <- melt(ARG_gene_ab, id = colnames(ARG_gene_ab)[1]) %>% 
  rename(Name = variable, Abundance = value) %>% 
  merge(metadata,by="Name")
```

```{r}
#Identifying the top 20 ARGs
ARG_sum <- ARG_ab_metadata %>% 
  group_by(ARG_group) %>%
  summarize(sum_genes=sum(Abundance))

top20 <- top_n(ARG_sum,20)
top20
```

```{r}
#Barplot of the top 20 ARGs
ARG_ab_barplot <- ARG_ab_metadata %>% 
  filter(ARG_group %in% top20$ARG_group) %>% 
  ggbarplot(x= "Time_tx", y = "Abundance", color = "ARG_group", fill = "ARG_group", 
            palette = get_palette("rickandmorty",20), 
            ylab = "Abundance score", 
            legend = "right", 
            position = position_stack()) +
  labs(fill="ARG", color="ARG") +
  facet_grid(~Treatment, scales = "free_x", space = "free_x") +
  guides(color = guide_legend(ncol = 2, bycol = TRUE)) +
  theme(axis.text.x = element_text(angle = 90), axis.title.x = element_blank()) +  
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(legend.text = element_text(face = "italic"))

ARG_ab_barplot
```

```{r fig.height=4, fig.width=14}
ARG_composition_plots <- ggarrange(bray_plotARG, ARG_class_ab_barplot, ncol = 2, labels = c("C","D"), widths = c(1,.8))
ARG_composition_plots
```

